"""
Django settings for saloonweb project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from django.contrib.messages import constants as messages
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'media'),
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lsnal5g08l#m5jeqp7!(&zr0u@8aa-!i-jl9o9ak@zff!02ei!'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = True


# Email backend to use for sending emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# SMTP server settings
EMAIL_HOST = 'smtp.gmail.com'  # Replace with your SMTP server
EMAIL_PORT = 587  # For TLS, use 465 for SSL
EMAIL_USE_TLS = True  # Use TLS
EMAIL_USE_SSL = False  # Use SSL (False if using TLS)
EMAIL_HOST_USER = 'businessbhoumic@gmail.com'  # Your email address
EMAIL_HOST_PASSWORD = 'mvxn lnap accr bhld'  # Your email password

# Default email address to use for various automated correspondence from the site manager(s)
DEFAULT_FROM_EMAIL = 'businessbhoumic@gmail.com'


ALLOWED_HOSTS = ['bhoumic-app-3c37b115b439.herokuapp.com', 'localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'ckeditor',
    'ckeditor_uploader',
    'users',
    'booking.apps.BookingConfig',
    'pages.apps.PagesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}

# Media settings
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Redirect URLs after login/logout
LOGIN_REDIRECT_URL = 'users/profile/'
LOGIN_URL = '/users/signin/'
LOGOUT_REDIRECT_URL = 'users/signin/'

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'saloonweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            "pages/templates",
            "users/templates",
            "booking/templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'saloonweb.wsgi.application'


# Email backend to use for sending emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# SMTP server settings
EMAIL_HOST = 'smtp.gmail.com'  # Replace with your SMTP server
EMAIL_PORT = 587  # For TLS, use 465 for SSL
EMAIL_USE_TLS = True  # Use TLS
EMAIL_USE_SSL = False  # Use SSL (False if using TLS)
EMAIL_HOST_USER = 'businessbhoumic@gmail.com'  # Your email address
EMAIL_HOST_PASSWORD = 'mvxn lnap accr bhld'  # Your email password

# Default email address to use for various automated correspondence from the site manager(s)
DEFAULT_FROM_EMAIL = 'businessbhoumic@gmail.com'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'saloonwebdb',  # Name of the PostgreSQL database
        'USER': 'postgres',  # PostgreSQL username
        'PASSWORD': '##KhushiKaku1234',  # PostgreSQL password
        'HOST': 'localhost',  # Set to empty string for localhost
        'PORT': '5432',  # Set to empty string for default
    },
    'old': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

