# Generated by Django 5.0.6 on 2024-06-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.CharField(help_text='Duration of the service', max_length=50),
        ),
    ]
