# Generated by Django 5.0.6 on 2024-07-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
